name: udisks2
version: 2.1.7-1
summary: D-Bus service to access and manipulate storage devices
description: |
    The udisks project provides a daemon, tools and libraries to access
    and manipulate disks and storage devices.

    Please find the source code for this snap at:
    https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/udisks
grade: stable
confinement: strict

apps:
    udisksctl:
        command: bin/udisksctl
        plugs: [client]
    udisksd:
        daemon: simple
        command: libexec/udisks2/udisksd
        slots: [service]
        plugs: [mount-observe]

slots:
    service:
        interface: udisks2

plugs:
    client:
        interface: udisks2
parts:
    udisks2:
        plugin: autotools
        source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/udisks2
        source-type: git
        source-branch: udisks/2.1.7
        configflags:
            - --enable-fhs-media
        install-via: destdir
        build-packages:
            - pkg-config
            - xsltproc
            - gtk-doc-tools
            - intltool
            - libglib2.0-dev
            - udev
            - libgudev-1.0-dev
            - libpolkit-gobject-1-dev
            - libpolkit-agent-1-dev
            - libacl1-dev
            - libgirepository1.0-dev
            - gobject-introspection
            - libatasmart-dev
            - libsystemd-dev
        stage-packages:
            - libacl1
            - libatasmart4
            - libglib2.0-0
            - libgudev-1.0-0
            - libpam-systemd
            - libpolkit-agent-1-0
            - libpolkit-gobject-1-0
            - parted
        filesets:
            licenses:
                - usr/share/doc/*/*copyright*
            binaries:
                - bin/udisksctl
                - libexec/udisks2/udisksd
        snap:
            - $binaries
            - $licenses
            - lib
            - -lib/pkgconfig
            - -lib/systemd
            - -lib/cgmanager
            - libexec
            - sbin
            - usr/lib/*/*.so*

