name: udisks2
version: 2.1.7-4
summary: D-Bus service to access and manipulate storage devices
description: |
    The udisks project provides a daemon, tools and libraries to access
    and manipulate disks and storage devices.

    Please find the source code for this snap at:
    https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/udisks
grade: stable
confinement: strict

apps:
    udisksctl:
        command: bin/udisksctl
        plugs: [client]
        aliases: [udisksctl]
    udisksd:
        daemon: simple
        command: libexec/udisks2/udisksd
        slots: [service]
        plugs:
            - hardware-observe
            - mount-observe
    ciborium:
        daemon: simple
        command: bin/ciborium.sh
        plugs:
            - client
            - network-bind

slots:
    service:
        interface: udisks2

plugs:
    client:
        interface: udisks2
parts:
    udisks2:
        plugin: autotools
        source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/udisks2
        source-type: git
        source-branch: udisks/2.1.7
        configflags:
            - --enable-fhs-media
        install-via: destdir
        build-packages:
            - pkg-config
            - xsltproc
            - gtk-doc-tools
            - intltool
            - libglib2.0-dev
            - udev
            - libgudev-1.0-dev
            - libpolkit-gobject-1-dev
            - libpolkit-agent-1-dev
            - libacl1-dev
            - libgirepository1.0-dev
            - gobject-introspection
            - libatasmart-dev
            - libsystemd-dev
        stage-packages:
            - libacl1
            - libatasmart4
            - libglib2.0-0
            - libgudev-1.0-0
            - libpam-systemd
            - libpolkit-agent-1-0
            - libpolkit-gobject-1-0
            - parted
        filesets:
            licenses:
                - usr/share/doc/*/*copyright*
            binaries:
                - bin/udisksctl
                - libexec/udisks2/udisksd
        prime:
            - $binaries
            - $licenses
            - lib
            - -lib/pkgconfig
            - -lib/systemd
            - -lib/cgmanager
            - libexec
            - sbin
            - usr/lib/*/*.so*
    ciborium:
        plugin: go
        go-importpath: launchpad.net/ciborium
        source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/udisks2
        source-type: git
        source-branch: ciborium/0.2.12
        build-packages:
            - bzr
            - libqt5opengl5-dev
            - pkg-config
            - qtbase5-private-dev
            - qtdeclarative5-private-dev
        filesets:
            licenses:
                - usr/share/doc/*/*copyright*
            binaries:
                - bin/ciborium
        prime:
            - $binaries
            - $licenses
    ciborium-launcher:
        plugin: dump
        source: bin
        organize:
            ciborium.sh: bin/ciborium.sh

